
development:
  adapter: postgresql
  encoding: unicode
  database: francislofts_dev
  pool: 5
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: francislofts_test
  pool: 5
  host: localhost
